// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module nn_inference_hwmm_layer3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_address0,
        input_0_ce0,
        input_0_q0,
        input_0_address1,
        input_0_ce1,
        input_0_q1,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] input_0_address0;
output   input_0_ce0;
input  [31:0] input_0_q0;
output  [3:0] input_0_address1;
output   input_0_ce1;
input  [31:0] input_0_q1;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] input_0_address0;
reg input_0_ce0;
reg[3:0] input_0_address1;
reg input_0_ce1;
reg[31:0] ap_return_0;
reg[31:0] ap_return_1;
reg[31:0] ap_return_2;
reg[31:0] ap_return_3;
reg[31:0] ap_return_4;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg  signed [31:0] reg_389;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [31:0] tmp_s_reg_3138;
reg   [31:0] tmp_15_reg_3153;
reg   [29:0] tmp_reg_3158;
reg   [28:0] tmp_29_reg_3163;
reg   [31:0] tmp_58_reg_3168;
reg   [31:0] tmp_2_reg_3173;
reg   [31:0] tmp_17_reg_3188;
reg   [31:0] tmp_31_reg_3193;
reg   [31:0] tmp_45_reg_3198;
reg   [31:0] tmp_60_reg_3203;
reg   [31:0] tmp_4_reg_3208;
reg   [31:0] tmp_19_reg_3223;
reg   [31:0] tmp_33_reg_3228;
reg   [31:0] tmp_47_reg_3233;
reg   [31:0] tmp_62_reg_3238;
reg   [31:0] tmp_6_reg_3243;
reg   [31:0] tmp_21_reg_3258;
reg   [31:0] tmp_35_reg_3263;
reg   [31:0] tmp_49_reg_3268;
reg   [31:0] tmp_64_reg_3273;
reg   [31:0] tmp_8_reg_3278;
reg   [31:0] tmp_23_reg_3293;
reg   [31:0] tmp_37_reg_3298;
reg   [31:0] tmp_51_reg_3303;
reg   [31:0] tmp_66_reg_3308;
reg   [31:0] tmp_10_reg_3313;
reg   [31:0] tmp_25_reg_3328;
reg   [31:0] tmp_39_reg_3333;
reg   [31:0] tmp_53_reg_3338;
reg   [31:0] tmp_68_reg_3343;
reg   [31:0] tmp_12_reg_3348;
reg   [31:0] tmp_27_reg_3358;
reg   [31:0] tmp_41_reg_3363;
reg   [31:0] tmp_55_reg_3368;
reg   [31:0] tmp_70_reg_3373;
wire  signed [22:0] r_V_8_fu_410_p1;
wire   [53:0] r_V_8_fu_410_p2;
wire  signed [31:0] sext_ln1115_10_fu_438_p0;
wire  signed [31:0] r_V_10_fu_442_p0;
wire  signed [54:0] sext_ln1115_10_fu_438_p1;
wire   [23:0] r_V_10_fu_442_p1;
wire   [29:0] trunc_ln_fu_416_p4;
wire   [53:0] lhs_fu_448_p3;
wire   [54:0] r_V_10_fu_442_p2;
wire  signed [55:0] sext_ln728_fu_456_p1;
wire  signed [55:0] sext_ln703_fu_460_p1;
wire   [55:0] ret_V_fu_464_p2;
wire  signed [31:0] r_V_39_fu_480_p0;
wire  signed [54:0] sext_ln1115_5_fu_402_p1;
wire   [23:0] r_V_39_fu_480_p1;
wire   [54:0] r_V_39_fu_480_p2;
wire  signed [31:0] r_V_40_fu_496_p0;
wire   [23:0] r_V_40_fu_496_p1;
wire   [30:0] trunc_ln708_s_fu_486_p4;
wire   [54:0] lhs_20_fu_502_p3;
wire   [54:0] r_V_40_fu_496_p2;
wire  signed [55:0] sext_ln728_1_fu_510_p1;
wire  signed [55:0] sext_ln703_10_fu_514_p1;
wire   [55:0] ret_V_19_fu_518_p2;
wire   [20:0] r_V_55_fu_534_p1;
wire   [51:0] r_V_55_fu_534_p2;
wire   [21:0] r_V_56_fu_550_p1;
wire   [27:0] trunc_ln708_1_fu_540_p4;
wire   [51:0] lhs_35_fu_556_p3;
wire   [52:0] r_V_56_fu_550_p2;
wire  signed [53:0] sext_ln1192_fu_564_p1;
wire  signed [53:0] sext_ln1192_1_fu_568_p1;
wire   [53:0] ret_V_34_fu_572_p2;
wire  signed [19:0] r_V_71_fu_588_p1;
wire   [50:0] r_V_71_fu_588_p2;
wire   [20:0] r_V_72_fu_604_p1;
wire   [26:0] trunc_ln708_2_fu_594_p4;
wire   [50:0] lhs_50_fu_610_p3;
wire   [51:0] r_V_72_fu_604_p2;
wire  signed [52:0] sext_ln1192_2_fu_618_p1;
wire  signed [52:0] sext_ln1192_3_fu_622_p1;
wire   [52:0] ret_V_49_fu_626_p2;
wire  signed [31:0] r_V_87_fu_642_p0;
wire   [23:0] r_V_87_fu_642_p1;
wire   [54:0] r_V_87_fu_642_p2;
wire   [22:0] r_V_88_fu_658_p1;
wire   [30:0] trunc_ln708_3_fu_648_p4;
wire   [54:0] lhs_65_fu_664_p3;
wire   [53:0] r_V_88_fu_658_p2;
wire  signed [55:0] sext_ln728_4_fu_672_p1;
wire  signed [55:0] sext_ln703_40_fu_676_p1;
wire   [55:0] ret_V_64_fu_680_p2;
wire  signed [22:0] r_V_12_fu_712_p1;
wire   [53:0] r_V_12_fu_712_p2;
wire   [55:0] lhs_6_fu_718_p3;
wire  signed [55:0] sext_ln703_1_fu_725_p1;
wire  signed [31:0] sext_ln1115_16_fu_739_p0;
wire  signed [31:0] sext_ln1115_17_fu_743_p0;
wire  signed [31:0] r_V_14_fu_747_p0;
wire  signed [55:0] sext_ln1115_17_fu_743_p1;
wire   [24:0] r_V_14_fu_747_p1;
wire   [55:0] ret_V_5_fu_729_p2;
wire   [31:0] tmp_1_fu_753_p4;
wire   [55:0] lhs_7_fu_763_p3;
wire   [55:0] r_V_14_fu_747_p2;
wire   [55:0] ret_V_6_fu_771_p2;
wire  signed [21:0] r_V_41_fu_787_p1;
wire   [52:0] r_V_41_fu_787_p2;
wire   [55:0] lhs_21_fu_793_p3;
wire  signed [55:0] sext_ln703_11_fu_800_p1;
wire  signed [31:0] r_V_42_fu_810_p0;
wire  signed [54:0] sext_ln1115_16_fu_739_p1;
wire   [23:0] r_V_42_fu_810_p1;
wire   [55:0] ret_V_20_fu_804_p2;
wire   [31:0] tmp_16_fu_816_p4;
wire   [54:0] r_V_42_fu_810_p2;
wire   [55:0] lhs_22_fu_826_p3;
wire  signed [55:0] sext_ln703_12_fu_834_p1;
wire   [55:0] ret_V_21_fu_838_p2;
wire  signed [31:0] r_V_57_fu_854_p0;
wire  signed [54:0] sext_ln1115_12_fu_700_p1;
wire  signed [23:0] r_V_57_fu_854_p1;
wire   [53:0] tmp_14_fu_860_p3;
wire   [54:0] r_V_57_fu_854_p2;
wire  signed [55:0] lhs_36_fu_867_p1;
wire  signed [55:0] sext_ln703_22_fu_871_p1;
wire  signed [31:0] r_V_58_fu_881_p0;
wire   [23:0] r_V_58_fu_881_p1;
wire   [55:0] ret_V_35_fu_875_p2;
wire   [31:0] tmp_30_fu_887_p4;
wire   [54:0] r_V_58_fu_881_p2;
wire   [55:0] lhs_37_fu_897_p3;
wire  signed [55:0] sext_ln703_23_fu_905_p1;
wire   [55:0] ret_V_36_fu_909_p2;
wire  signed [31:0] r_V_73_fu_925_p0;
wire  signed [23:0] r_V_73_fu_925_p1;
wire   [52:0] tmp_43_fu_931_p3;
wire   [54:0] r_V_73_fu_925_p2;
wire  signed [55:0] lhs_51_fu_938_p1;
wire  signed [55:0] sext_ln703_31_fu_942_p1;
wire   [20:0] r_V_74_fu_952_p1;
wire   [55:0] ret_V_50_fu_946_p2;
wire   [31:0] tmp_44_fu_958_p4;
wire   [51:0] r_V_74_fu_952_p2;
wire   [55:0] lhs_52_fu_968_p3;
wire  signed [55:0] sext_ln703_32_fu_976_p1;
wire   [55:0] ret_V_51_fu_980_p2;
wire   [24:0] r_V_89_fu_996_p1;
wire   [55:0] lhs_66_fu_1002_p3;
wire   [55:0] r_V_89_fu_996_p2;
wire  signed [31:0] r_V_90_fu_1015_p0;
wire  signed [25:0] r_V_90_fu_1015_p1;
wire   [55:0] ret_V_65_fu_1009_p2;
wire   [31:0] tmp_59_fu_1021_p4;
wire   [55:0] lhs_67_fu_1031_p3;
wire   [55:0] r_V_90_fu_1015_p2;
wire   [55:0] ret_V_66_fu_1039_p2;
wire  signed [31:0] r_V_16_fu_1067_p0;
wire  signed [54:0] sext_ln1115_20_fu_1063_p1;
wire  signed [23:0] r_V_16_fu_1067_p1;
wire   [54:0] r_V_16_fu_1067_p2;
wire   [55:0] lhs_8_fu_1073_p3;
wire  signed [55:0] sext_ln703_2_fu_1080_p1;
wire  signed [31:0] sext_ln1115_21_fu_1090_p0;
wire  signed [19:0] r_V_18_fu_1102_p1;
wire   [55:0] ret_V_7_fu_1084_p2;
wire   [31:0] tmp_3_fu_1108_p4;
wire   [50:0] r_V_18_fu_1102_p2;
wire   [55:0] lhs_9_fu_1118_p3;
wire  signed [55:0] sext_ln703_3_fu_1126_p1;
wire   [55:0] ret_V_8_fu_1130_p2;
wire  signed [31:0] r_V_43_fu_1146_p0;
wire   [23:0] r_V_43_fu_1146_p1;
wire   [54:0] r_V_43_fu_1146_p2;
wire   [55:0] lhs_23_fu_1152_p3;
wire  signed [55:0] sext_ln703_13_fu_1159_p1;
wire  signed [21:0] r_V_44_fu_1169_p1;
wire   [55:0] ret_V_22_fu_1163_p2;
wire   [31:0] tmp_18_fu_1175_p4;
wire   [52:0] r_V_44_fu_1169_p2;
wire   [55:0] lhs_24_fu_1185_p3;
wire  signed [55:0] sext_ln703_14_fu_1193_p1;
wire   [55:0] ret_V_23_fu_1197_p2;
wire  signed [20:0] r_V_59_fu_1213_p1;
wire   [51:0] r_V_59_fu_1213_p2;
wire   [55:0] lhs_38_fu_1219_p3;
wire  signed [55:0] sext_ln703_24_fu_1226_p1;
wire  signed [31:0] r_V_60_fu_1236_p0;
wire  signed [55:0] sext_ln1115_21_fu_1090_p1;
wire  signed [25:0] r_V_60_fu_1236_p1;
wire   [55:0] ret_V_37_fu_1230_p2;
wire   [31:0] tmp_32_fu_1242_p4;
wire   [55:0] lhs_39_fu_1252_p3;
wire   [55:0] r_V_60_fu_1236_p2;
wire   [55:0] ret_V_38_fu_1260_p2;
wire  signed [31:0] r_V_75_fu_1276_p0;
wire   [23:0] r_V_75_fu_1276_p1;
wire   [54:0] r_V_75_fu_1276_p2;
wire   [55:0] lhs_53_fu_1282_p3;
wire  signed [55:0] sext_ln703_33_fu_1289_p1;
wire  signed [31:0] r_V_76_fu_1299_p0;
wire   [25:0] r_V_76_fu_1299_p1;
wire   [55:0] ret_V_52_fu_1293_p2;
wire   [31:0] tmp_46_fu_1305_p4;
wire   [55:0] lhs_54_fu_1315_p3;
wire   [55:0] r_V_76_fu_1299_p2;
wire   [55:0] ret_V_53_fu_1323_p2;
wire  signed [25:0] r_V_91_fu_1339_p1;
wire   [55:0] lhs_68_fu_1345_p3;
wire   [55:0] r_V_91_fu_1339_p2;
wire  signed [31:0] r_V_92_fu_1358_p0;
wire   [24:0] r_V_92_fu_1358_p1;
wire   [55:0] ret_V_67_fu_1352_p2;
wire   [31:0] tmp_61_fu_1364_p4;
wire   [55:0] lhs_69_fu_1374_p3;
wire   [55:0] r_V_92_fu_1358_p2;
wire   [55:0] ret_V_68_fu_1382_p2;
wire  signed [31:0] r_V_20_fu_1406_p0;
wire  signed [54:0] sext_ln1115_25_fu_1402_p1;
wire  signed [23:0] r_V_20_fu_1406_p1;
wire   [54:0] r_V_20_fu_1406_p2;
wire   [55:0] lhs_10_fu_1412_p3;
wire  signed [55:0] sext_ln703_4_fu_1419_p1;
wire  signed [31:0] sext_ln1115_26_fu_1429_p0;
wire  signed [31:0] sext_ln1115_27_fu_1433_p0;
wire  signed [31:0] r_V_22_fu_1437_p0;
wire  signed [55:0] sext_ln1115_27_fu_1433_p1;
wire   [24:0] r_V_22_fu_1437_p1;
wire   [55:0] ret_V_9_fu_1423_p2;
wire   [31:0] tmp_5_fu_1443_p4;
wire   [55:0] lhs_11_fu_1453_p3;
wire   [55:0] r_V_22_fu_1437_p2;
wire   [55:0] ret_V_10_fu_1461_p2;
wire  signed [31:0] r_V_45_fu_1477_p0;
wire  signed [23:0] r_V_45_fu_1477_p1;
wire   [54:0] r_V_45_fu_1477_p2;
wire   [55:0] lhs_25_fu_1483_p3;
wire  signed [55:0] sext_ln703_15_fu_1490_p1;
wire  signed [31:0] r_V_46_fu_1500_p0;
wire   [24:0] r_V_46_fu_1500_p1;
wire   [55:0] ret_V_24_fu_1494_p2;
wire   [31:0] tmp_20_fu_1506_p4;
wire   [55:0] lhs_26_fu_1516_p3;
wire   [55:0] r_V_46_fu_1500_p2;
wire   [55:0] ret_V_25_fu_1524_p2;
wire  signed [31:0] r_V_61_fu_1540_p0;
wire  signed [55:0] sext_ln1115_24_fu_1398_p1;
wire   [24:0] r_V_61_fu_1540_p1;
wire   [55:0] lhs_40_fu_1546_p3;
wire   [55:0] r_V_61_fu_1540_p2;
wire  signed [31:0] r_V_62_fu_1559_p0;
wire  signed [25:0] r_V_62_fu_1559_p1;
wire   [55:0] ret_V_39_fu_1553_p2;
wire   [31:0] tmp_34_fu_1565_p4;
wire   [55:0] lhs_41_fu_1575_p3;
wire   [55:0] r_V_62_fu_1559_p2;
wire   [55:0] ret_V_40_fu_1583_p2;
wire  signed [31:0] r_V_77_fu_1599_p0;
wire  signed [24:0] r_V_77_fu_1599_p1;
wire   [55:0] lhs_55_fu_1605_p3;
wire   [55:0] r_V_77_fu_1599_p2;
wire  signed [31:0] r_V_78_fu_1618_p0;
wire  signed [54:0] sext_ln1115_26_fu_1429_p1;
wire   [23:0] r_V_78_fu_1618_p1;
wire   [55:0] ret_V_54_fu_1612_p2;
wire   [31:0] tmp_48_fu_1624_p4;
wire   [54:0] r_V_78_fu_1618_p2;
wire   [55:0] lhs_56_fu_1634_p3;
wire  signed [55:0] sext_ln703_34_fu_1642_p1;
wire   [55:0] ret_V_55_fu_1646_p2;
wire  signed [31:0] r_V_93_fu_1662_p0;
wire  signed [23:0] r_V_93_fu_1662_p1;
wire   [54:0] r_V_93_fu_1662_p2;
wire   [55:0] lhs_70_fu_1668_p3;
wire  signed [55:0] sext_ln703_41_fu_1675_p1;
wire  signed [31:0] r_V_94_fu_1685_p0;
wire  signed [23:0] r_V_94_fu_1685_p1;
wire   [55:0] ret_V_69_fu_1679_p2;
wire   [31:0] tmp_63_fu_1691_p4;
wire   [54:0] r_V_94_fu_1685_p2;
wire   [55:0] lhs_71_fu_1701_p3;
wire  signed [55:0] sext_ln703_42_fu_1709_p1;
wire   [55:0] ret_V_70_fu_1713_p2;
wire  signed [31:0] r_V_24_fu_1737_p0;
wire  signed [55:0] sext_ln1115_29_fu_1733_p1;
wire   [24:0] r_V_24_fu_1737_p1;
wire   [55:0] lhs_12_fu_1743_p3;
wire   [55:0] r_V_24_fu_1737_p2;
wire  signed [31:0] r_V_26_fu_1760_p0;
wire  signed [55:0] sext_ln1115_30_fu_1756_p1;
wire  signed [25:0] r_V_26_fu_1760_p1;
wire   [55:0] ret_V_11_fu_1750_p2;
wire   [31:0] tmp_7_fu_1766_p4;
wire   [55:0] lhs_13_fu_1776_p3;
wire   [55:0] r_V_26_fu_1760_p2;
wire   [55:0] ret_V_12_fu_1784_p2;
wire  signed [31:0] r_V_47_fu_1800_p0;
wire  signed [24:0] r_V_47_fu_1800_p1;
wire   [55:0] lhs_27_fu_1806_p3;
wire   [55:0] r_V_47_fu_1800_p2;
wire  signed [31:0] r_V_48_fu_1819_p0;
wire  signed [25:0] r_V_48_fu_1819_p1;
wire   [55:0] ret_V_26_fu_1813_p2;
wire   [31:0] tmp_22_fu_1825_p4;
wire   [55:0] lhs_28_fu_1835_p3;
wire   [55:0] r_V_48_fu_1819_p2;
wire   [55:0] ret_V_27_fu_1843_p2;
wire  signed [31:0] r_V_63_fu_1859_p0;
wire   [25:0] r_V_63_fu_1859_p1;
wire   [55:0] lhs_42_fu_1865_p3;
wire   [55:0] r_V_63_fu_1859_p2;
wire  signed [31:0] r_V_64_fu_1878_p0;
wire   [24:0] r_V_64_fu_1878_p1;
wire   [55:0] ret_V_41_fu_1872_p2;
wire   [31:0] tmp_36_fu_1884_p4;
wire   [55:0] lhs_43_fu_1894_p3;
wire   [55:0] r_V_64_fu_1878_p2;
wire   [55:0] ret_V_42_fu_1902_p2;
wire  signed [31:0] r_V_79_fu_1918_p0;
wire  signed [25:0] r_V_79_fu_1918_p1;
wire   [55:0] lhs_57_fu_1924_p3;
wire   [55:0] r_V_79_fu_1918_p2;
wire  signed [31:0] r_V_80_fu_1937_p0;
wire   [25:0] r_V_80_fu_1937_p1;
wire   [55:0] ret_V_56_fu_1931_p2;
wire   [31:0] tmp_50_fu_1943_p4;
wire   [55:0] lhs_58_fu_1953_p3;
wire   [55:0] r_V_80_fu_1937_p2;
wire   [55:0] ret_V_57_fu_1961_p2;
wire  signed [21:0] r_V_95_fu_1977_p1;
wire   [52:0] r_V_95_fu_1977_p2;
wire   [55:0] lhs_72_fu_1983_p3;
wire  signed [55:0] sext_ln703_43_fu_1990_p1;
wire  signed [31:0] r_V_96_fu_2000_p0;
wire   [24:0] r_V_96_fu_2000_p1;
wire   [55:0] ret_V_71_fu_1994_p2;
wire   [31:0] tmp_65_fu_2006_p4;
wire   [55:0] lhs_73_fu_2016_p3;
wire   [55:0] r_V_96_fu_2000_p2;
wire   [55:0] ret_V_72_fu_2024_p2;
wire  signed [31:0] r_V_28_fu_2048_p0;
wire  signed [54:0] sext_ln1115_32_fu_2044_p1;
wire  signed [23:0] r_V_28_fu_2048_p1;
wire   [54:0] r_V_28_fu_2048_p2;
wire   [55:0] lhs_14_fu_2054_p3;
wire  signed [55:0] sext_ln703_5_fu_2061_p1;
wire  signed [31:0] sext_ln1115_34_fu_2075_p0;
wire  signed [22:0] r_V_30_fu_2087_p1;
wire   [55:0] ret_V_13_fu_2065_p2;
wire   [31:0] tmp_9_fu_2093_p4;
wire   [53:0] r_V_30_fu_2087_p2;
wire   [55:0] lhs_15_fu_2103_p3;
wire  signed [55:0] sext_ln703_6_fu_2111_p1;
wire   [55:0] ret_V_14_fu_2115_p2;
wire  signed [31:0] r_V_49_fu_2131_p0;
wire  signed [23:0] r_V_49_fu_2131_p1;
wire   [54:0] r_V_49_fu_2131_p2;
wire   [55:0] lhs_29_fu_2137_p3;
wire  signed [55:0] sext_ln703_16_fu_2144_p1;
wire   [21:0] r_V_50_fu_2154_p1;
wire   [55:0] ret_V_28_fu_2148_p2;
wire   [31:0] tmp_24_fu_2160_p4;
wire   [52:0] r_V_50_fu_2154_p2;
wire   [55:0] lhs_30_fu_2170_p3;
wire  signed [55:0] sext_ln703_17_fu_2178_p1;
wire   [55:0] ret_V_29_fu_2182_p2;
wire   [22:0] r_V_65_fu_2198_p1;
wire   [53:0] r_V_65_fu_2198_p2;
wire   [55:0] lhs_44_fu_2204_p3;
wire  signed [55:0] sext_ln703_25_fu_2211_p1;
wire  signed [31:0] r_V_66_fu_2221_p0;
wire  signed [50:0] sext_ln1115_34_fu_2075_p1;
wire   [19:0] r_V_66_fu_2221_p1;
wire   [55:0] ret_V_43_fu_2215_p2;
wire   [31:0] tmp_38_fu_2227_p4;
wire   [50:0] r_V_66_fu_2221_p2;
wire   [55:0] lhs_45_fu_2237_p3;
wire  signed [55:0] sext_ln703_26_fu_2245_p1;
wire   [55:0] ret_V_44_fu_2249_p2;
wire  signed [31:0] r_V_81_fu_2265_p0;
wire  signed [23:0] r_V_81_fu_2265_p1;
wire   [54:0] r_V_81_fu_2265_p2;
wire   [55:0] lhs_59_fu_2271_p3;
wire  signed [55:0] sext_ln703_35_fu_2278_p1;
wire   [23:0] r_V_82_fu_2288_p1;
wire   [55:0] ret_V_58_fu_2282_p2;
wire   [31:0] tmp_52_fu_2294_p4;
wire   [54:0] r_V_82_fu_2288_p2;
wire   [55:0] lhs_60_fu_2304_p3;
wire  signed [55:0] sext_ln703_36_fu_2312_p1;
wire   [55:0] ret_V_59_fu_2316_p2;
wire  signed [31:0] r_V_97_fu_2332_p0;
wire  signed [23:0] r_V_97_fu_2332_p1;
wire   [54:0] r_V_97_fu_2332_p2;
wire   [55:0] lhs_74_fu_2338_p3;
wire  signed [55:0] sext_ln703_44_fu_2345_p1;
wire  signed [31:0] r_V_98_fu_2355_p0;
wire  signed [18:0] r_V_98_fu_2355_p1;
wire   [55:0] ret_V_73_fu_2349_p2;
wire   [31:0] tmp_67_fu_2361_p4;
wire   [50:0] r_V_98_fu_2355_p2;
wire   [55:0] lhs_75_fu_2371_p3;
wire  signed [55:0] sext_ln703_45_fu_2379_p1;
wire   [55:0] ret_V_74_fu_2383_p2;
wire  signed [31:0] r_V_32_fu_2407_p0;
wire  signed [54:0] sext_ln1115_38_fu_2403_p1;
wire   [23:0] r_V_32_fu_2407_p1;
wire   [54:0] r_V_32_fu_2407_p2;
wire   [55:0] lhs_16_fu_2413_p3;
wire  signed [55:0] sext_ln703_7_fu_2420_p1;
wire  signed [31:0] sext_ln1115_39_fu_2430_p0;
wire  signed [31:0] sext_ln1115_40_fu_2434_p0;
wire  signed [21:0] r_V_34_fu_2442_p1;
wire   [55:0] ret_V_15_fu_2424_p2;
wire   [31:0] tmp_11_fu_2448_p4;
wire   [52:0] r_V_34_fu_2442_p2;
wire   [55:0] lhs_17_fu_2458_p3;
wire  signed [55:0] sext_ln703_8_fu_2466_p1;
wire   [55:0] ret_V_16_fu_2470_p2;
wire  signed [20:0] r_V_51_fu_2486_p1;
wire   [51:0] r_V_51_fu_2486_p2;
wire   [55:0] lhs_31_fu_2492_p3;
wire  signed [55:0] sext_ln703_18_fu_2499_p1;
wire  signed [31:0] r_V_52_fu_2509_p0;
wire  signed [54:0] sext_ln1115_40_fu_2434_p1;
wire   [23:0] r_V_52_fu_2509_p1;
wire   [55:0] ret_V_30_fu_2503_p2;
wire   [31:0] tmp_26_fu_2515_p4;
wire   [54:0] r_V_52_fu_2509_p2;
wire   [55:0] lhs_32_fu_2525_p3;
wire  signed [55:0] sext_ln703_19_fu_2533_p1;
wire   [55:0] ret_V_31_fu_2537_p2;
wire  signed [31:0] r_V_67_fu_2553_p0;
wire  signed [23:0] r_V_67_fu_2553_p1;
wire   [54:0] r_V_67_fu_2553_p2;
wire   [55:0] lhs_46_fu_2559_p3;
wire  signed [55:0] sext_ln703_27_fu_2566_p1;
wire  signed [31:0] r_V_68_fu_2576_p0;
wire  signed [53:0] sext_ln1115_39_fu_2430_p1;
wire  signed [22:0] r_V_68_fu_2576_p1;
wire   [55:0] ret_V_45_fu_2570_p2;
wire   [31:0] tmp_40_fu_2582_p4;
wire   [53:0] r_V_68_fu_2576_p2;
wire   [55:0] lhs_47_fu_2592_p3;
wire  signed [55:0] sext_ln703_28_fu_2600_p1;
wire   [55:0] ret_V_46_fu_2604_p2;
wire  signed [31:0] r_V_83_fu_2620_p0;
wire  signed [23:0] r_V_83_fu_2620_p1;
wire   [54:0] r_V_83_fu_2620_p2;
wire   [55:0] lhs_61_fu_2626_p3;
wire  signed [55:0] sext_ln703_37_fu_2633_p1;
wire  signed [31:0] r_V_84_fu_2643_p0;
wire  signed [22:0] r_V_84_fu_2643_p1;
wire   [55:0] ret_V_60_fu_2637_p2;
wire   [31:0] tmp_54_fu_2649_p4;
wire   [53:0] r_V_84_fu_2643_p2;
wire   [55:0] lhs_62_fu_2659_p3;
wire  signed [55:0] sext_ln703_38_fu_2667_p1;
wire   [55:0] ret_V_61_fu_2671_p2;
wire  signed [31:0] r_V_99_fu_2687_p0;
wire   [23:0] r_V_99_fu_2687_p1;
wire   [54:0] r_V_99_fu_2687_p2;
wire   [55:0] lhs_76_fu_2693_p3;
wire  signed [55:0] sext_ln703_46_fu_2700_p1;
wire  signed [31:0] r_V_100_fu_2710_p0;
wire  signed [23:0] r_V_100_fu_2710_p1;
wire   [55:0] ret_V_75_fu_2704_p2;
wire   [31:0] tmp_69_fu_2716_p4;
wire   [54:0] r_V_100_fu_2710_p2;
wire   [55:0] lhs_77_fu_2726_p3;
wire  signed [55:0] sext_ln703_47_fu_2734_p1;
wire   [55:0] ret_V_76_fu_2738_p2;
wire    ap_CS_fsm_state10;
wire  signed [31:0] r_V_36_fu_2762_p0;
wire  signed [55:0] sext_ln1115_43_fu_2758_p1;
wire  signed [24:0] r_V_36_fu_2762_p1;
wire   [55:0] lhs_18_fu_2768_p3;
wire   [55:0] r_V_36_fu_2762_p2;
wire  signed [31:0] sext_ln1115_44_fu_2781_p0;
wire  signed [20:0] r_V_38_fu_2789_p1;
wire   [55:0] ret_V_17_fu_2775_p2;
wire   [31:0] tmp_13_fu_2795_p4;
wire   [51:0] r_V_38_fu_2789_p2;
wire   [55:0] lhs_19_fu_2805_p3;
wire  signed [55:0] sext_ln703_9_fu_2813_p1;
wire   [55:0] ret_V_18_fu_2817_p2;
wire  signed [31:0] r_V_53_fu_2833_p0;
wire  signed [54:0] sext_ln1115_42_fu_2754_p1;
wire   [23:0] r_V_53_fu_2833_p1;
wire   [54:0] r_V_53_fu_2833_p2;
wire   [55:0] lhs_33_fu_2839_p3;
wire  signed [55:0] sext_ln703_20_fu_2846_p1;
wire  signed [31:0] r_V_54_fu_2856_p0;
wire  signed [54:0] sext_ln1115_44_fu_2781_p1;
wire  signed [23:0] r_V_54_fu_2856_p1;
wire   [55:0] ret_V_32_fu_2850_p2;
wire   [31:0] tmp_28_fu_2862_p4;
wire   [54:0] r_V_54_fu_2856_p2;
wire   [55:0] lhs_34_fu_2872_p3;
wire  signed [55:0] sext_ln703_21_fu_2880_p1;
wire   [55:0] ret_V_33_fu_2884_p2;
wire  signed [31:0] r_V_69_fu_2900_p0;
wire  signed [23:0] r_V_69_fu_2900_p1;
wire   [54:0] r_V_69_fu_2900_p2;
wire   [55:0] lhs_48_fu_2906_p3;
wire  signed [55:0] sext_ln703_29_fu_2913_p1;
wire  signed [31:0] r_V_70_fu_2923_p0;
wire  signed [23:0] r_V_70_fu_2923_p1;
wire   [55:0] ret_V_47_fu_2917_p2;
wire   [31:0] tmp_42_fu_2929_p4;
wire   [54:0] r_V_70_fu_2923_p2;
wire   [55:0] lhs_49_fu_2939_p3;
wire  signed [55:0] sext_ln703_30_fu_2947_p1;
wire   [55:0] ret_V_48_fu_2951_p2;
wire  signed [31:0] r_V_85_fu_2967_p0;
wire   [24:0] r_V_85_fu_2967_p1;
wire   [55:0] lhs_63_fu_2973_p3;
wire   [55:0] r_V_85_fu_2967_p2;
wire  signed [31:0] r_V_86_fu_2986_p0;
wire   [23:0] r_V_86_fu_2986_p1;
wire   [55:0] ret_V_62_fu_2980_p2;
wire   [31:0] tmp_56_fu_2992_p4;
wire   [54:0] r_V_86_fu_2986_p2;
wire   [55:0] lhs_64_fu_3002_p3;
wire  signed [55:0] sext_ln703_39_fu_3010_p1;
wire   [55:0] ret_V_63_fu_3014_p2;
wire  signed [31:0] r_V_101_fu_3030_p0;
wire   [25:0] r_V_101_fu_3030_p1;
wire   [55:0] lhs_78_fu_3036_p3;
wire   [55:0] r_V_101_fu_3030_p2;
wire  signed [31:0] r_V_102_fu_3049_p0;
wire   [23:0] r_V_102_fu_3049_p1;
wire   [55:0] ret_V_77_fu_3043_p2;
wire   [31:0] tmp_71_fu_3055_p4;
wire   [54:0] r_V_102_fu_3049_p2;
wire   [55:0] lhs_79_fu_3065_p3;
wire  signed [55:0] sext_ln703_48_fu_3073_p1;
wire   [55:0] ret_V_78_fu_3077_p2;
reg   [31:0] ap_return_0_preg;
reg   [31:0] ap_return_1_preg;
reg   [31:0] ap_return_2_preg;
reg   [31:0] ap_return_3_preg;
reg   [31:0] ap_return_4_preg;
reg   [9:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_return_0_preg = 32'd0;
#0 ap_return_1_preg = 32'd0;
#0 ap_return_2_preg = 32'd0;
#0 ap_return_3_preg = 32'd0;
#0 ap_return_4_preg = 32'd0;
end

nn_inference_mul_32s_23s_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 54 ))
mul_32s_23s_54_1_1_U20(
    .din0(reg_389),
    .din1(r_V_8_fu_410_p1),
    .dout(r_V_8_fu_410_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U21(
    .din0(r_V_10_fu_442_p0),
    .din1(r_V_10_fu_442_p1),
    .dout(r_V_10_fu_442_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U22(
    .din0(r_V_39_fu_480_p0),
    .din1(r_V_39_fu_480_p1),
    .dout(r_V_39_fu_480_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U23(
    .din0(r_V_40_fu_496_p0),
    .din1(r_V_40_fu_496_p1),
    .dout(r_V_40_fu_496_p2)
);

nn_inference_mul_32s_21ns_52_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21ns_52_1_1_U24(
    .din0(reg_389),
    .din1(r_V_55_fu_534_p1),
    .dout(r_V_55_fu_534_p2)
);

nn_inference_mul_32s_22ns_53_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 53 ))
mul_32s_22ns_53_1_1_U25(
    .din0(input_0_q1),
    .din1(r_V_56_fu_550_p1),
    .dout(r_V_56_fu_550_p2)
);

nn_inference_mul_32s_20s_51_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 20 ),
    .dout_WIDTH( 51 ))
mul_32s_20s_51_1_1_U26(
    .din0(reg_389),
    .din1(r_V_71_fu_588_p1),
    .dout(r_V_71_fu_588_p2)
);

nn_inference_mul_32s_21ns_52_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21ns_52_1_1_U27(
    .din0(input_0_q1),
    .din1(r_V_72_fu_604_p1),
    .dout(r_V_72_fu_604_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U28(
    .din0(r_V_87_fu_642_p0),
    .din1(r_V_87_fu_642_p1),
    .dout(r_V_87_fu_642_p2)
);

nn_inference_mul_32s_23ns_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 54 ))
mul_32s_23ns_54_1_1_U29(
    .din0(input_0_q1),
    .din1(r_V_88_fu_658_p1),
    .dout(r_V_88_fu_658_p2)
);

nn_inference_mul_32s_23s_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 54 ))
mul_32s_23s_54_1_1_U30(
    .din0(reg_389),
    .din1(r_V_12_fu_712_p1),
    .dout(r_V_12_fu_712_p2)
);

nn_inference_mul_32s_25ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 56 ))
mul_32s_25ns_56_1_1_U31(
    .din0(r_V_14_fu_747_p0),
    .din1(r_V_14_fu_747_p1),
    .dout(r_V_14_fu_747_p2)
);

nn_inference_mul_32s_22s_53_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 53 ))
mul_32s_22s_53_1_1_U32(
    .din0(reg_389),
    .din1(r_V_41_fu_787_p1),
    .dout(r_V_41_fu_787_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U33(
    .din0(r_V_42_fu_810_p0),
    .din1(r_V_42_fu_810_p1),
    .dout(r_V_42_fu_810_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U34(
    .din0(r_V_57_fu_854_p0),
    .din1(r_V_57_fu_854_p1),
    .dout(r_V_57_fu_854_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U35(
    .din0(r_V_58_fu_881_p0),
    .din1(r_V_58_fu_881_p1),
    .dout(r_V_58_fu_881_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U36(
    .din0(r_V_73_fu_925_p0),
    .din1(r_V_73_fu_925_p1),
    .dout(r_V_73_fu_925_p2)
);

nn_inference_mul_32s_21ns_52_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21ns_52_1_1_U37(
    .din0(input_0_q0),
    .din1(r_V_74_fu_952_p1),
    .dout(r_V_74_fu_952_p2)
);

nn_inference_mul_32s_25ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 56 ))
mul_32s_25ns_56_1_1_U38(
    .din0(reg_389),
    .din1(r_V_89_fu_996_p1),
    .dout(r_V_89_fu_996_p2)
);

nn_inference_mul_32s_26s_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 56 ))
mul_32s_26s_56_1_1_U39(
    .din0(r_V_90_fu_1015_p0),
    .din1(r_V_90_fu_1015_p1),
    .dout(r_V_90_fu_1015_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U40(
    .din0(r_V_16_fu_1067_p0),
    .din1(r_V_16_fu_1067_p1),
    .dout(r_V_16_fu_1067_p2)
);

nn_inference_mul_32s_20s_51_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 20 ),
    .dout_WIDTH( 51 ))
mul_32s_20s_51_1_1_U41(
    .din0(input_0_q0),
    .din1(r_V_18_fu_1102_p1),
    .dout(r_V_18_fu_1102_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U42(
    .din0(r_V_43_fu_1146_p0),
    .din1(r_V_43_fu_1146_p1),
    .dout(r_V_43_fu_1146_p2)
);

nn_inference_mul_32s_22s_53_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 53 ))
mul_32s_22s_53_1_1_U43(
    .din0(input_0_q0),
    .din1(r_V_44_fu_1169_p1),
    .dout(r_V_44_fu_1169_p2)
);

nn_inference_mul_32s_21s_52_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21s_52_1_1_U44(
    .din0(reg_389),
    .din1(r_V_59_fu_1213_p1),
    .dout(r_V_59_fu_1213_p2)
);

nn_inference_mul_32s_26s_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 56 ))
mul_32s_26s_56_1_1_U45(
    .din0(r_V_60_fu_1236_p0),
    .din1(r_V_60_fu_1236_p1),
    .dout(r_V_60_fu_1236_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U46(
    .din0(r_V_75_fu_1276_p0),
    .din1(r_V_75_fu_1276_p1),
    .dout(r_V_75_fu_1276_p2)
);

nn_inference_mul_32s_26ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 56 ))
mul_32s_26ns_56_1_1_U47(
    .din0(r_V_76_fu_1299_p0),
    .din1(r_V_76_fu_1299_p1),
    .dout(r_V_76_fu_1299_p2)
);

nn_inference_mul_32s_26s_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 56 ))
mul_32s_26s_56_1_1_U48(
    .din0(reg_389),
    .din1(r_V_91_fu_1339_p1),
    .dout(r_V_91_fu_1339_p2)
);

nn_inference_mul_32s_25ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 56 ))
mul_32s_25ns_56_1_1_U49(
    .din0(r_V_92_fu_1358_p0),
    .din1(r_V_92_fu_1358_p1),
    .dout(r_V_92_fu_1358_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U50(
    .din0(r_V_20_fu_1406_p0),
    .din1(r_V_20_fu_1406_p1),
    .dout(r_V_20_fu_1406_p2)
);

nn_inference_mul_32s_25ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 56 ))
mul_32s_25ns_56_1_1_U51(
    .din0(r_V_22_fu_1437_p0),
    .din1(r_V_22_fu_1437_p1),
    .dout(r_V_22_fu_1437_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U52(
    .din0(r_V_45_fu_1477_p0),
    .din1(r_V_45_fu_1477_p1),
    .dout(r_V_45_fu_1477_p2)
);

nn_inference_mul_32s_25ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 56 ))
mul_32s_25ns_56_1_1_U53(
    .din0(r_V_46_fu_1500_p0),
    .din1(r_V_46_fu_1500_p1),
    .dout(r_V_46_fu_1500_p2)
);

nn_inference_mul_32s_25ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 56 ))
mul_32s_25ns_56_1_1_U54(
    .din0(r_V_61_fu_1540_p0),
    .din1(r_V_61_fu_1540_p1),
    .dout(r_V_61_fu_1540_p2)
);

nn_inference_mul_32s_26s_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 56 ))
mul_32s_26s_56_1_1_U55(
    .din0(r_V_62_fu_1559_p0),
    .din1(r_V_62_fu_1559_p1),
    .dout(r_V_62_fu_1559_p2)
);

nn_inference_mul_32s_25s_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 56 ))
mul_32s_25s_56_1_1_U56(
    .din0(r_V_77_fu_1599_p0),
    .din1(r_V_77_fu_1599_p1),
    .dout(r_V_77_fu_1599_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U57(
    .din0(r_V_78_fu_1618_p0),
    .din1(r_V_78_fu_1618_p1),
    .dout(r_V_78_fu_1618_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U58(
    .din0(r_V_93_fu_1662_p0),
    .din1(r_V_93_fu_1662_p1),
    .dout(r_V_93_fu_1662_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U59(
    .din0(r_V_94_fu_1685_p0),
    .din1(r_V_94_fu_1685_p1),
    .dout(r_V_94_fu_1685_p2)
);

nn_inference_mul_32s_25ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 56 ))
mul_32s_25ns_56_1_1_U60(
    .din0(r_V_24_fu_1737_p0),
    .din1(r_V_24_fu_1737_p1),
    .dout(r_V_24_fu_1737_p2)
);

nn_inference_mul_32s_26s_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 56 ))
mul_32s_26s_56_1_1_U61(
    .din0(r_V_26_fu_1760_p0),
    .din1(r_V_26_fu_1760_p1),
    .dout(r_V_26_fu_1760_p2)
);

nn_inference_mul_32s_25s_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 56 ))
mul_32s_25s_56_1_1_U62(
    .din0(r_V_47_fu_1800_p0),
    .din1(r_V_47_fu_1800_p1),
    .dout(r_V_47_fu_1800_p2)
);

nn_inference_mul_32s_26s_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 56 ))
mul_32s_26s_56_1_1_U63(
    .din0(r_V_48_fu_1819_p0),
    .din1(r_V_48_fu_1819_p1),
    .dout(r_V_48_fu_1819_p2)
);

nn_inference_mul_32s_26ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 56 ))
mul_32s_26ns_56_1_1_U64(
    .din0(r_V_63_fu_1859_p0),
    .din1(r_V_63_fu_1859_p1),
    .dout(r_V_63_fu_1859_p2)
);

nn_inference_mul_32s_25ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 56 ))
mul_32s_25ns_56_1_1_U65(
    .din0(r_V_64_fu_1878_p0),
    .din1(r_V_64_fu_1878_p1),
    .dout(r_V_64_fu_1878_p2)
);

nn_inference_mul_32s_26s_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 56 ))
mul_32s_26s_56_1_1_U66(
    .din0(r_V_79_fu_1918_p0),
    .din1(r_V_79_fu_1918_p1),
    .dout(r_V_79_fu_1918_p2)
);

nn_inference_mul_32s_26ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 56 ))
mul_32s_26ns_56_1_1_U67(
    .din0(r_V_80_fu_1937_p0),
    .din1(r_V_80_fu_1937_p1),
    .dout(r_V_80_fu_1937_p2)
);

nn_inference_mul_32s_22s_53_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 53 ))
mul_32s_22s_53_1_1_U68(
    .din0(reg_389),
    .din1(r_V_95_fu_1977_p1),
    .dout(r_V_95_fu_1977_p2)
);

nn_inference_mul_32s_25ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 56 ))
mul_32s_25ns_56_1_1_U69(
    .din0(r_V_96_fu_2000_p0),
    .din1(r_V_96_fu_2000_p1),
    .dout(r_V_96_fu_2000_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U70(
    .din0(r_V_28_fu_2048_p0),
    .din1(r_V_28_fu_2048_p1),
    .dout(r_V_28_fu_2048_p2)
);

nn_inference_mul_32s_23s_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 54 ))
mul_32s_23s_54_1_1_U71(
    .din0(input_0_q0),
    .din1(r_V_30_fu_2087_p1),
    .dout(r_V_30_fu_2087_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U72(
    .din0(r_V_49_fu_2131_p0),
    .din1(r_V_49_fu_2131_p1),
    .dout(r_V_49_fu_2131_p2)
);

nn_inference_mul_32s_22ns_53_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 53 ))
mul_32s_22ns_53_1_1_U73(
    .din0(input_0_q0),
    .din1(r_V_50_fu_2154_p1),
    .dout(r_V_50_fu_2154_p2)
);

nn_inference_mul_32s_23ns_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 54 ))
mul_32s_23ns_54_1_1_U74(
    .din0(reg_389),
    .din1(r_V_65_fu_2198_p1),
    .dout(r_V_65_fu_2198_p2)
);

nn_inference_mul_32s_20ns_51_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 20 ),
    .dout_WIDTH( 51 ))
mul_32s_20ns_51_1_1_U75(
    .din0(r_V_66_fu_2221_p0),
    .din1(r_V_66_fu_2221_p1),
    .dout(r_V_66_fu_2221_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U76(
    .din0(r_V_81_fu_2265_p0),
    .din1(r_V_81_fu_2265_p1),
    .dout(r_V_81_fu_2265_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U77(
    .din0(input_0_q0),
    .din1(r_V_82_fu_2288_p1),
    .dout(r_V_82_fu_2288_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U78(
    .din0(r_V_97_fu_2332_p0),
    .din1(r_V_97_fu_2332_p1),
    .dout(r_V_97_fu_2332_p2)
);

nn_inference_mul_32s_19s_51_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 19 ),
    .dout_WIDTH( 51 ))
mul_32s_19s_51_1_1_U79(
    .din0(r_V_98_fu_2355_p0),
    .din1(r_V_98_fu_2355_p1),
    .dout(r_V_98_fu_2355_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U80(
    .din0(r_V_32_fu_2407_p0),
    .din1(r_V_32_fu_2407_p1),
    .dout(r_V_32_fu_2407_p2)
);

nn_inference_mul_32s_22s_53_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 53 ))
mul_32s_22s_53_1_1_U81(
    .din0(input_0_q0),
    .din1(r_V_34_fu_2442_p1),
    .dout(r_V_34_fu_2442_p2)
);

nn_inference_mul_32s_21s_52_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21s_52_1_1_U82(
    .din0(reg_389),
    .din1(r_V_51_fu_2486_p1),
    .dout(r_V_51_fu_2486_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U83(
    .din0(r_V_52_fu_2509_p0),
    .din1(r_V_52_fu_2509_p1),
    .dout(r_V_52_fu_2509_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U84(
    .din0(r_V_67_fu_2553_p0),
    .din1(r_V_67_fu_2553_p1),
    .dout(r_V_67_fu_2553_p2)
);

nn_inference_mul_32s_23s_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 54 ))
mul_32s_23s_54_1_1_U85(
    .din0(r_V_68_fu_2576_p0),
    .din1(r_V_68_fu_2576_p1),
    .dout(r_V_68_fu_2576_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U86(
    .din0(r_V_83_fu_2620_p0),
    .din1(r_V_83_fu_2620_p1),
    .dout(r_V_83_fu_2620_p2)
);

nn_inference_mul_32s_23s_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 54 ))
mul_32s_23s_54_1_1_U87(
    .din0(r_V_84_fu_2643_p0),
    .din1(r_V_84_fu_2643_p1),
    .dout(r_V_84_fu_2643_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U88(
    .din0(r_V_99_fu_2687_p0),
    .din1(r_V_99_fu_2687_p1),
    .dout(r_V_99_fu_2687_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U89(
    .din0(r_V_100_fu_2710_p0),
    .din1(r_V_100_fu_2710_p1),
    .dout(r_V_100_fu_2710_p2)
);

nn_inference_mul_32s_25s_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 56 ))
mul_32s_25s_56_1_1_U90(
    .din0(r_V_36_fu_2762_p0),
    .din1(r_V_36_fu_2762_p1),
    .dout(r_V_36_fu_2762_p2)
);

nn_inference_mul_32s_21s_52_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 52 ))
mul_32s_21s_52_1_1_U91(
    .din0(input_0_q1),
    .din1(r_V_38_fu_2789_p1),
    .dout(r_V_38_fu_2789_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U92(
    .din0(r_V_53_fu_2833_p0),
    .din1(r_V_53_fu_2833_p1),
    .dout(r_V_53_fu_2833_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U93(
    .din0(r_V_54_fu_2856_p0),
    .din1(r_V_54_fu_2856_p1),
    .dout(r_V_54_fu_2856_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U94(
    .din0(r_V_69_fu_2900_p0),
    .din1(r_V_69_fu_2900_p1),
    .dout(r_V_69_fu_2900_p2)
);

nn_inference_mul_32s_24s_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_1_1_U95(
    .din0(r_V_70_fu_2923_p0),
    .din1(r_V_70_fu_2923_p1),
    .dout(r_V_70_fu_2923_p2)
);

nn_inference_mul_32s_25ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 56 ))
mul_32s_25ns_56_1_1_U96(
    .din0(r_V_85_fu_2967_p0),
    .din1(r_V_85_fu_2967_p1),
    .dout(r_V_85_fu_2967_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U97(
    .din0(r_V_86_fu_2986_p0),
    .din1(r_V_86_fu_2986_p1),
    .dout(r_V_86_fu_2986_p2)
);

nn_inference_mul_32s_26ns_56_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 56 ))
mul_32s_26ns_56_1_1_U98(
    .din0(r_V_101_fu_3030_p0),
    .din1(r_V_101_fu_3030_p1),
    .dout(r_V_101_fu_3030_p2)
);

nn_inference_mul_32s_24ns_55_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24ns_55_1_1_U99(
    .din0(r_V_102_fu_3049_p0),
    .din1(r_V_102_fu_3049_p1),
    .dout(r_V_102_fu_3049_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_return_0_preg <= {{ret_V_18_fu_2817_p2[55:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_return_1_preg <= {{ret_V_33_fu_2884_p2[55:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_return_2_preg <= {{ret_V_48_fu_2951_p2[55:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_return_3_preg <= {{ret_V_63_fu_3014_p2[55:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_return_4_preg <= {{ret_V_78_fu_3077_p2[55:24]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        reg_389 <= input_0_q1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        reg_389 <= input_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_10_reg_3313 <= {{ret_V_14_fu_2115_p2[55:24]}};
        tmp_25_reg_3328 <= {{ret_V_29_fu_2182_p2[55:24]}};
        tmp_39_reg_3333 <= {{ret_V_44_fu_2249_p2[55:24]}};
        tmp_53_reg_3338 <= {{ret_V_59_fu_2316_p2[55:24]}};
        tmp_68_reg_3343 <= {{ret_V_74_fu_2383_p2[55:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tmp_12_reg_3348 <= {{ret_V_16_fu_2470_p2[55:24]}};
        tmp_27_reg_3358 <= {{ret_V_31_fu_2537_p2[55:24]}};
        tmp_41_reg_3363 <= {{ret_V_46_fu_2604_p2[55:24]}};
        tmp_55_reg_3368 <= {{ret_V_61_fu_2671_p2[55:24]}};
        tmp_70_reg_3373 <= {{ret_V_76_fu_2738_p2[55:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_15_reg_3153 <= {{ret_V_19_fu_518_p2[55:24]}};
        tmp_29_reg_3163 <= {{ret_V_49_fu_626_p2[52:24]}};
        tmp_58_reg_3168 <= {{ret_V_64_fu_680_p2[55:24]}};
        tmp_reg_3158 <= {{ret_V_34_fu_572_p2[53:24]}};
        tmp_s_reg_3138 <= {{ret_V_fu_464_p2[55:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_17_reg_3188 <= {{ret_V_21_fu_838_p2[55:24]}};
        tmp_2_reg_3173 <= {{ret_V_6_fu_771_p2[55:24]}};
        tmp_31_reg_3193 <= {{ret_V_36_fu_909_p2[55:24]}};
        tmp_45_reg_3198 <= {{ret_V_51_fu_980_p2[55:24]}};
        tmp_60_reg_3203 <= {{ret_V_66_fu_1039_p2[55:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_19_reg_3223 <= {{ret_V_23_fu_1197_p2[55:24]}};
        tmp_33_reg_3228 <= {{ret_V_38_fu_1260_p2[55:24]}};
        tmp_47_reg_3233 <= {{ret_V_53_fu_1323_p2[55:24]}};
        tmp_4_reg_3208 <= {{ret_V_8_fu_1130_p2[55:24]}};
        tmp_62_reg_3238 <= {{ret_V_68_fu_1382_p2[55:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_21_reg_3258 <= {{ret_V_25_fu_1524_p2[55:24]}};
        tmp_35_reg_3263 <= {{ret_V_40_fu_1583_p2[55:24]}};
        tmp_49_reg_3268 <= {{ret_V_55_fu_1646_p2[55:24]}};
        tmp_64_reg_3273 <= {{ret_V_70_fu_1713_p2[55:24]}};
        tmp_6_reg_3243 <= {{ret_V_10_fu_1461_p2[55:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_23_reg_3293 <= {{ret_V_27_fu_1843_p2[55:24]}};
        tmp_37_reg_3298 <= {{ret_V_42_fu_1902_p2[55:24]}};
        tmp_51_reg_3303 <= {{ret_V_57_fu_1961_p2[55:24]}};
        tmp_66_reg_3308 <= {{ret_V_72_fu_2024_p2[55:24]}};
        tmp_8_reg_3278 <= {{ret_V_12_fu_1784_p2[55:24]}};
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_return_0 = {{ret_V_18_fu_2817_p2[55:24]}};
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_return_1 = {{ret_V_33_fu_2884_p2[55:24]}};
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_return_2 = {{ret_V_48_fu_2951_p2[55:24]}};
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_return_3 = {{ret_V_63_fu_3014_p2[55:24]}};
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_return_4 = {{ret_V_78_fu_3077_p2[55:24]}};
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        input_0_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        input_0_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        input_0_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        input_0_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_0_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_0_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_0_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        input_0_address0 = 64'd0;
    end else begin
        input_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        input_0_address1 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        input_0_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        input_0_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        input_0_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        input_0_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_0_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_0_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_0_address1 = 64'd1;
    end else begin
        input_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        input_0_ce0 = 1'b1;
    end else begin
        input_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        input_0_ce1 = 1'b1;
    end else begin
        input_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign lhs_10_fu_1412_p3 = {{tmp_4_reg_3208}, {24'd0}};

assign lhs_11_fu_1453_p3 = {{tmp_5_fu_1443_p4}, {24'd0}};

assign lhs_12_fu_1743_p3 = {{tmp_6_reg_3243}, {24'd0}};

assign lhs_13_fu_1776_p3 = {{tmp_7_fu_1766_p4}, {24'd0}};

assign lhs_14_fu_2054_p3 = {{tmp_8_reg_3278}, {24'd0}};

assign lhs_15_fu_2103_p3 = {{tmp_9_fu_2093_p4}, {24'd0}};

assign lhs_16_fu_2413_p3 = {{tmp_10_reg_3313}, {24'd0}};

assign lhs_17_fu_2458_p3 = {{tmp_11_fu_2448_p4}, {24'd0}};

assign lhs_18_fu_2768_p3 = {{tmp_12_reg_3348}, {24'd0}};

assign lhs_19_fu_2805_p3 = {{tmp_13_fu_2795_p4}, {24'd0}};

assign lhs_20_fu_502_p3 = {{trunc_ln708_s_fu_486_p4}, {24'd0}};

assign lhs_21_fu_793_p3 = {{tmp_15_reg_3153}, {24'd0}};

assign lhs_22_fu_826_p3 = {{tmp_16_fu_816_p4}, {24'd0}};

assign lhs_23_fu_1152_p3 = {{tmp_17_reg_3188}, {24'd0}};

assign lhs_24_fu_1185_p3 = {{tmp_18_fu_1175_p4}, {24'd0}};

assign lhs_25_fu_1483_p3 = {{tmp_19_reg_3223}, {24'd0}};

assign lhs_26_fu_1516_p3 = {{tmp_20_fu_1506_p4}, {24'd0}};

assign lhs_27_fu_1806_p3 = {{tmp_21_reg_3258}, {24'd0}};

assign lhs_28_fu_1835_p3 = {{tmp_22_fu_1825_p4}, {24'd0}};

assign lhs_29_fu_2137_p3 = {{tmp_23_reg_3293}, {24'd0}};

assign lhs_30_fu_2170_p3 = {{tmp_24_fu_2160_p4}, {24'd0}};

assign lhs_31_fu_2492_p3 = {{tmp_25_reg_3328}, {24'd0}};

assign lhs_32_fu_2525_p3 = {{tmp_26_fu_2515_p4}, {24'd0}};

assign lhs_33_fu_2839_p3 = {{tmp_27_reg_3358}, {24'd0}};

assign lhs_34_fu_2872_p3 = {{tmp_28_fu_2862_p4}, {24'd0}};

assign lhs_35_fu_556_p3 = {{trunc_ln708_1_fu_540_p4}, {24'd0}};

assign lhs_36_fu_867_p1 = $signed(tmp_14_fu_860_p3);

assign lhs_37_fu_897_p3 = {{tmp_30_fu_887_p4}, {24'd0}};

assign lhs_38_fu_1219_p3 = {{tmp_31_reg_3193}, {24'd0}};

assign lhs_39_fu_1252_p3 = {{tmp_32_fu_1242_p4}, {24'd0}};

assign lhs_40_fu_1546_p3 = {{tmp_33_reg_3228}, {24'd0}};

assign lhs_41_fu_1575_p3 = {{tmp_34_fu_1565_p4}, {24'd0}};

assign lhs_42_fu_1865_p3 = {{tmp_35_reg_3263}, {24'd0}};

assign lhs_43_fu_1894_p3 = {{tmp_36_fu_1884_p4}, {24'd0}};

assign lhs_44_fu_2204_p3 = {{tmp_37_reg_3298}, {24'd0}};

assign lhs_45_fu_2237_p3 = {{tmp_38_fu_2227_p4}, {24'd0}};

assign lhs_46_fu_2559_p3 = {{tmp_39_reg_3333}, {24'd0}};

assign lhs_47_fu_2592_p3 = {{tmp_40_fu_2582_p4}, {24'd0}};

assign lhs_48_fu_2906_p3 = {{tmp_41_reg_3363}, {24'd0}};

assign lhs_49_fu_2939_p3 = {{tmp_42_fu_2929_p4}, {24'd0}};

assign lhs_50_fu_610_p3 = {{trunc_ln708_2_fu_594_p4}, {24'd0}};

assign lhs_51_fu_938_p1 = $signed(tmp_43_fu_931_p3);

assign lhs_52_fu_968_p3 = {{tmp_44_fu_958_p4}, {24'd0}};

assign lhs_53_fu_1282_p3 = {{tmp_45_reg_3198}, {24'd0}};

assign lhs_54_fu_1315_p3 = {{tmp_46_fu_1305_p4}, {24'd0}};

assign lhs_55_fu_1605_p3 = {{tmp_47_reg_3233}, {24'd0}};

assign lhs_56_fu_1634_p3 = {{tmp_48_fu_1624_p4}, {24'd0}};

assign lhs_57_fu_1924_p3 = {{tmp_49_reg_3268}, {24'd0}};

assign lhs_58_fu_1953_p3 = {{tmp_50_fu_1943_p4}, {24'd0}};

assign lhs_59_fu_2271_p3 = {{tmp_51_reg_3303}, {24'd0}};

assign lhs_60_fu_2304_p3 = {{tmp_52_fu_2294_p4}, {24'd0}};

assign lhs_61_fu_2626_p3 = {{tmp_53_reg_3338}, {24'd0}};

assign lhs_62_fu_2659_p3 = {{tmp_54_fu_2649_p4}, {24'd0}};

assign lhs_63_fu_2973_p3 = {{tmp_55_reg_3368}, {24'd0}};

assign lhs_64_fu_3002_p3 = {{tmp_56_fu_2992_p4}, {24'd0}};

assign lhs_65_fu_664_p3 = {{trunc_ln708_3_fu_648_p4}, {24'd0}};

assign lhs_66_fu_1002_p3 = {{tmp_58_reg_3168}, {24'd0}};

assign lhs_67_fu_1031_p3 = {{tmp_59_fu_1021_p4}, {24'd0}};

assign lhs_68_fu_1345_p3 = {{tmp_60_reg_3203}, {24'd0}};

assign lhs_69_fu_1374_p3 = {{tmp_61_fu_1364_p4}, {24'd0}};

assign lhs_6_fu_718_p3 = {{tmp_s_reg_3138}, {24'd0}};

assign lhs_70_fu_1668_p3 = {{tmp_62_reg_3238}, {24'd0}};

assign lhs_71_fu_1701_p3 = {{tmp_63_fu_1691_p4}, {24'd0}};

assign lhs_72_fu_1983_p3 = {{tmp_64_reg_3273}, {24'd0}};

assign lhs_73_fu_2016_p3 = {{tmp_65_fu_2006_p4}, {24'd0}};

assign lhs_74_fu_2338_p3 = {{tmp_66_reg_3308}, {24'd0}};

assign lhs_75_fu_2371_p3 = {{tmp_67_fu_2361_p4}, {24'd0}};

assign lhs_76_fu_2693_p3 = {{tmp_68_reg_3343}, {24'd0}};

assign lhs_77_fu_2726_p3 = {{tmp_69_fu_2716_p4}, {24'd0}};

assign lhs_78_fu_3036_p3 = {{tmp_70_reg_3373}, {24'd0}};

assign lhs_79_fu_3065_p3 = {{tmp_71_fu_3055_p4}, {24'd0}};

assign lhs_7_fu_763_p3 = {{tmp_1_fu_753_p4}, {24'd0}};

assign lhs_8_fu_1073_p3 = {{tmp_2_reg_3173}, {24'd0}};

assign lhs_9_fu_1118_p3 = {{tmp_3_fu_1108_p4}, {24'd0}};

assign lhs_fu_448_p3 = {{trunc_ln_fu_416_p4}, {24'd0}};

assign r_V_100_fu_2710_p0 = sext_ln1115_40_fu_2434_p1;

assign r_V_100_fu_2710_p1 = 55'd36028797012807045;

assign r_V_101_fu_3030_p0 = sext_ln1115_43_fu_2758_p1;

assign r_V_101_fu_3030_p1 = 56'd19481324;

assign r_V_102_fu_3049_p0 = sext_ln1115_44_fu_2781_p1;

assign r_V_102_fu_3049_p1 = 55'd6168919;

assign r_V_10_fu_442_p0 = sext_ln1115_10_fu_438_p1;

assign r_V_10_fu_442_p1 = 55'd6918100;

assign r_V_12_fu_712_p1 = 54'd18014398506941719;

assign r_V_14_fu_747_p0 = sext_ln1115_17_fu_743_p1;

assign r_V_14_fu_747_p1 = 56'd8706412;

assign r_V_16_fu_1067_p0 = sext_ln1115_20_fu_1063_p1;

assign r_V_16_fu_1067_p1 = 55'd36028797013838939;

assign r_V_18_fu_1102_p1 = 51'd2251799813396841;

assign r_V_20_fu_1406_p0 = sext_ln1115_25_fu_1402_p1;

assign r_V_20_fu_1406_p1 = 55'd36028797011492827;

assign r_V_22_fu_1437_p0 = sext_ln1115_27_fu_1433_p1;

assign r_V_22_fu_1437_p1 = 56'd11180834;

assign r_V_24_fu_1737_p0 = sext_ln1115_29_fu_1733_p1;

assign r_V_24_fu_1737_p1 = 56'd10091797;

assign r_V_26_fu_1760_p0 = sext_ln1115_30_fu_1756_p1;

assign r_V_26_fu_1760_p1 = 56'd72057594020762087;

assign r_V_28_fu_2048_p0 = sext_ln1115_32_fu_2044_p1;

assign r_V_28_fu_2048_p1 = 55'd36028797010815814;

assign r_V_30_fu_2087_p1 = 54'd18014398507187413;

assign r_V_32_fu_2407_p0 = sext_ln1115_38_fu_2403_p1;

assign r_V_32_fu_2407_p1 = 55'd7732393;

assign r_V_34_fu_2442_p1 = 53'd9007199252988211;

assign r_V_36_fu_2762_p0 = sext_ln1115_43_fu_2758_p1;

assign r_V_36_fu_2762_p1 = 56'd72057594025381071;

assign r_V_38_fu_2789_p1 = 52'd4503599626373107;

assign r_V_39_fu_480_p0 = sext_ln1115_5_fu_402_p1;

assign r_V_39_fu_480_p1 = 55'd6816774;

assign r_V_40_fu_496_p0 = sext_ln1115_10_fu_438_p1;

assign r_V_40_fu_496_p1 = 55'd4713000;

assign r_V_41_fu_787_p1 = 53'd9007199253559209;

assign r_V_42_fu_810_p0 = sext_ln1115_16_fu_739_p1;

assign r_V_42_fu_810_p1 = 55'd8257035;

assign r_V_43_fu_1146_p0 = sext_ln1115_20_fu_1063_p1;

assign r_V_43_fu_1146_p1 = 55'd7722560;

assign r_V_44_fu_1169_p1 = 53'd9007199253295097;

assign r_V_45_fu_1477_p0 = sext_ln1115_25_fu_1402_p1;

assign r_V_45_fu_1477_p1 = 55'd36028797010839835;

assign r_V_46_fu_1500_p0 = sext_ln1115_27_fu_1433_p1;

assign r_V_46_fu_1500_p1 = 56'd9679945;

assign r_V_47_fu_1800_p0 = sext_ln1115_29_fu_1733_p1;

assign r_V_47_fu_1800_p1 = 56'd72057594022045089;

assign r_V_48_fu_1819_p0 = sext_ln1115_30_fu_1756_p1;

assign r_V_48_fu_1819_p1 = 56'd72057594014893595;

assign r_V_49_fu_2131_p0 = sext_ln1115_32_fu_2044_p1;

assign r_V_49_fu_2131_p1 = 55'd36028797014416864;

assign r_V_50_fu_2154_p1 = 53'd2082856;

assign r_V_51_fu_2486_p1 = 52'd4503599626748488;

assign r_V_52_fu_2509_p0 = sext_ln1115_40_fu_2434_p1;

assign r_V_52_fu_2509_p1 = 55'd7670463;

assign r_V_53_fu_2833_p0 = sext_ln1115_42_fu_2754_p1;

assign r_V_53_fu_2833_p1 = 55'd5436039;

assign r_V_54_fu_2856_p0 = sext_ln1115_44_fu_2781_p1;

assign r_V_54_fu_2856_p1 = 55'd36028797010614456;

assign r_V_55_fu_534_p1 = 52'd612602;

assign r_V_56_fu_550_p1 = 53'd1210970;

assign r_V_57_fu_854_p0 = sext_ln1115_12_fu_700_p1;

assign r_V_57_fu_854_p1 = 55'd36028797014635579;

assign r_V_58_fu_881_p0 = sext_ln1115_16_fu_739_p1;

assign r_V_58_fu_881_p1 = 55'd7393140;

assign r_V_59_fu_1213_p1 = 52'd4503599626777917;

assign r_V_60_fu_1236_p0 = sext_ln1115_21_fu_1090_p1;

assign r_V_60_fu_1236_p1 = 56'd72057594013625955;

assign r_V_61_fu_1540_p0 = sext_ln1115_24_fu_1398_p1;

assign r_V_61_fu_1540_p1 = 56'd11532532;

assign r_V_62_fu_1559_p0 = sext_ln1115_27_fu_1433_p1;

assign r_V_62_fu_1559_p1 = 56'd72057594019712023;

assign r_V_63_fu_1859_p0 = sext_ln1115_29_fu_1733_p1;

assign r_V_63_fu_1859_p1 = 56'd20767539;

assign r_V_64_fu_1878_p0 = sext_ln1115_30_fu_1756_p1;

assign r_V_64_fu_1878_p1 = 56'd15177372;

assign r_V_65_fu_2198_p1 = 54'd2676096;

assign r_V_66_fu_2221_p0 = sext_ln1115_34_fu_2075_p1;

assign r_V_66_fu_2221_p1 = 51'd364197;

assign r_V_67_fu_2553_p0 = sext_ln1115_38_fu_2403_p1;

assign r_V_67_fu_2553_p1 = 55'd36028797012820663;

assign r_V_68_fu_2576_p0 = sext_ln1115_39_fu_2430_p1;

assign r_V_68_fu_2576_p1 = 54'd18014398506911372;

assign r_V_69_fu_2900_p0 = sext_ln1115_42_fu_2754_p1;

assign r_V_69_fu_2900_p1 = 55'd36028797014316643;

assign r_V_70_fu_2923_p0 = sext_ln1115_44_fu_2781_p1;

assign r_V_70_fu_2923_p1 = 55'd36028797013008403;

assign r_V_71_fu_588_p1 = 51'd2251799813171716;

assign r_V_72_fu_604_p1 = 52'd999167;

assign r_V_73_fu_925_p0 = sext_ln1115_12_fu_700_p1;

assign r_V_73_fu_925_p1 = 55'd36028797012499700;

assign r_V_74_fu_952_p1 = 52'd930342;

assign r_V_75_fu_1276_p0 = sext_ln1115_20_fu_1063_p1;

assign r_V_75_fu_1276_p1 = 55'd6890572;

assign r_V_76_fu_1299_p0 = sext_ln1115_21_fu_1090_p1;

assign r_V_76_fu_1299_p1 = 56'd18568960;

assign r_V_77_fu_1599_p0 = sext_ln1115_24_fu_1398_p1;

assign r_V_77_fu_1599_p1 = 56'd72057594028760757;

assign r_V_78_fu_1618_p0 = sext_ln1115_26_fu_1429_p1;

assign r_V_78_fu_1618_p1 = 55'd4854522;

assign r_V_79_fu_1918_p0 = sext_ln1115_29_fu_1733_p1;

assign r_V_79_fu_1918_p1 = 56'd72057594016399724;

assign r_V_80_fu_1937_p0 = sext_ln1115_30_fu_1756_p1;

assign r_V_80_fu_1937_p1 = 56'd18161973;

assign r_V_81_fu_2265_p0 = sext_ln1115_32_fu_2044_p1;

assign r_V_81_fu_2265_p1 = 55'd36028797012248980;

assign r_V_82_fu_2288_p1 = 55'd6487696;

assign r_V_83_fu_2620_p0 = sext_ln1115_38_fu_2403_p1;

assign r_V_83_fu_2620_p1 = 55'd36028797011631985;

assign r_V_84_fu_2643_p0 = sext_ln1115_39_fu_2430_p1;

assign r_V_84_fu_2643_p1 = 54'd18014398506873343;

assign r_V_85_fu_2967_p0 = sext_ln1115_43_fu_2758_p1;

assign r_V_85_fu_2967_p1 = 56'd8527483;

assign r_V_86_fu_2986_p0 = sext_ln1115_44_fu_2781_p1;

assign r_V_86_fu_2986_p1 = 55'd6044983;

assign r_V_87_fu_642_p0 = sext_ln1115_5_fu_402_p1;

assign r_V_87_fu_642_p1 = 55'd7182862;

assign r_V_88_fu_658_p1 = 54'd2527255;

assign r_V_89_fu_996_p1 = 56'd13641510;

assign r_V_8_fu_410_p1 = 54'd18014398505952251;

assign r_V_90_fu_1015_p0 = sext_ln1115_17_fu_743_p1;

assign r_V_90_fu_1015_p1 = 56'd72057594020738159;

assign r_V_91_fu_1339_p1 = 56'd72057594005653040;

assign r_V_92_fu_1358_p0 = sext_ln1115_21_fu_1090_p1;

assign r_V_92_fu_1358_p1 = 56'd15291224;

assign r_V_93_fu_1662_p0 = sext_ln1115_25_fu_1402_p1;

assign r_V_93_fu_1662_p1 = 55'd36028797012512054;

assign r_V_94_fu_1685_p0 = sext_ln1115_26_fu_1429_p1;

assign r_V_94_fu_1685_p1 = 55'd36028797011478919;

assign r_V_95_fu_1977_p1 = 53'd9007199252905632;

assign r_V_96_fu_2000_p0 = sext_ln1115_30_fu_1756_p1;

assign r_V_96_fu_2000_p1 = 56'd13905819;

assign r_V_97_fu_2332_p0 = sext_ln1115_32_fu_2044_p1;

assign r_V_97_fu_2332_p1 = 55'd36028797012979620;

assign r_V_98_fu_2355_p0 = sext_ln1115_34_fu_2075_p1;

assign r_V_98_fu_2355_p1 = 51'd2251799813521621;

assign r_V_99_fu_2687_p0 = sext_ln1115_38_fu_2403_p1;

assign r_V_99_fu_2687_p1 = 55'd7867012;

assign ret_V_10_fu_1461_p2 = (lhs_11_fu_1453_p3 + r_V_22_fu_1437_p2);

assign ret_V_11_fu_1750_p2 = (lhs_12_fu_1743_p3 + r_V_24_fu_1737_p2);

assign ret_V_12_fu_1784_p2 = (lhs_13_fu_1776_p3 + r_V_26_fu_1760_p2);

assign ret_V_13_fu_2065_p2 = ($signed(lhs_14_fu_2054_p3) + $signed(sext_ln703_5_fu_2061_p1));

assign ret_V_14_fu_2115_p2 = ($signed(lhs_15_fu_2103_p3) + $signed(sext_ln703_6_fu_2111_p1));

assign ret_V_15_fu_2424_p2 = ($signed(lhs_16_fu_2413_p3) + $signed(sext_ln703_7_fu_2420_p1));

assign ret_V_16_fu_2470_p2 = ($signed(lhs_17_fu_2458_p3) + $signed(sext_ln703_8_fu_2466_p1));

assign ret_V_17_fu_2775_p2 = (lhs_18_fu_2768_p3 + r_V_36_fu_2762_p2);

assign ret_V_18_fu_2817_p2 = ($signed(lhs_19_fu_2805_p3) + $signed(sext_ln703_9_fu_2813_p1));

assign ret_V_19_fu_518_p2 = ($signed(sext_ln728_1_fu_510_p1) + $signed(sext_ln703_10_fu_514_p1));

assign ret_V_20_fu_804_p2 = ($signed(lhs_21_fu_793_p3) + $signed(sext_ln703_11_fu_800_p1));

assign ret_V_21_fu_838_p2 = ($signed(lhs_22_fu_826_p3) + $signed(sext_ln703_12_fu_834_p1));

assign ret_V_22_fu_1163_p2 = ($signed(lhs_23_fu_1152_p3) + $signed(sext_ln703_13_fu_1159_p1));

assign ret_V_23_fu_1197_p2 = ($signed(lhs_24_fu_1185_p3) + $signed(sext_ln703_14_fu_1193_p1));

assign ret_V_24_fu_1494_p2 = ($signed(lhs_25_fu_1483_p3) + $signed(sext_ln703_15_fu_1490_p1));

assign ret_V_25_fu_1524_p2 = (lhs_26_fu_1516_p3 + r_V_46_fu_1500_p2);

assign ret_V_26_fu_1813_p2 = (lhs_27_fu_1806_p3 + r_V_47_fu_1800_p2);

assign ret_V_27_fu_1843_p2 = (lhs_28_fu_1835_p3 + r_V_48_fu_1819_p2);

assign ret_V_28_fu_2148_p2 = ($signed(lhs_29_fu_2137_p3) + $signed(sext_ln703_16_fu_2144_p1));

assign ret_V_29_fu_2182_p2 = ($signed(lhs_30_fu_2170_p3) + $signed(sext_ln703_17_fu_2178_p1));

assign ret_V_30_fu_2503_p2 = ($signed(lhs_31_fu_2492_p3) + $signed(sext_ln703_18_fu_2499_p1));

assign ret_V_31_fu_2537_p2 = ($signed(lhs_32_fu_2525_p3) + $signed(sext_ln703_19_fu_2533_p1));

assign ret_V_32_fu_2850_p2 = ($signed(lhs_33_fu_2839_p3) + $signed(sext_ln703_20_fu_2846_p1));

assign ret_V_33_fu_2884_p2 = ($signed(lhs_34_fu_2872_p3) + $signed(sext_ln703_21_fu_2880_p1));

assign ret_V_34_fu_572_p2 = ($signed(sext_ln1192_fu_564_p1) + $signed(sext_ln1192_1_fu_568_p1));

assign ret_V_35_fu_875_p2 = ($signed(lhs_36_fu_867_p1) + $signed(sext_ln703_22_fu_871_p1));

assign ret_V_36_fu_909_p2 = ($signed(lhs_37_fu_897_p3) + $signed(sext_ln703_23_fu_905_p1));

assign ret_V_37_fu_1230_p2 = ($signed(lhs_38_fu_1219_p3) + $signed(sext_ln703_24_fu_1226_p1));

assign ret_V_38_fu_1260_p2 = (lhs_39_fu_1252_p3 + r_V_60_fu_1236_p2);

assign ret_V_39_fu_1553_p2 = (lhs_40_fu_1546_p3 + r_V_61_fu_1540_p2);

assign ret_V_40_fu_1583_p2 = (lhs_41_fu_1575_p3 + r_V_62_fu_1559_p2);

assign ret_V_41_fu_1872_p2 = (lhs_42_fu_1865_p3 + r_V_63_fu_1859_p2);

assign ret_V_42_fu_1902_p2 = (lhs_43_fu_1894_p3 + r_V_64_fu_1878_p2);

assign ret_V_43_fu_2215_p2 = ($signed(lhs_44_fu_2204_p3) + $signed(sext_ln703_25_fu_2211_p1));

assign ret_V_44_fu_2249_p2 = ($signed(lhs_45_fu_2237_p3) + $signed(sext_ln703_26_fu_2245_p1));

assign ret_V_45_fu_2570_p2 = ($signed(lhs_46_fu_2559_p3) + $signed(sext_ln703_27_fu_2566_p1));

assign ret_V_46_fu_2604_p2 = ($signed(lhs_47_fu_2592_p3) + $signed(sext_ln703_28_fu_2600_p1));

assign ret_V_47_fu_2917_p2 = ($signed(lhs_48_fu_2906_p3) + $signed(sext_ln703_29_fu_2913_p1));

assign ret_V_48_fu_2951_p2 = ($signed(lhs_49_fu_2939_p3) + $signed(sext_ln703_30_fu_2947_p1));

assign ret_V_49_fu_626_p2 = ($signed(sext_ln1192_2_fu_618_p1) + $signed(sext_ln1192_3_fu_622_p1));

assign ret_V_50_fu_946_p2 = ($signed(lhs_51_fu_938_p1) + $signed(sext_ln703_31_fu_942_p1));

assign ret_V_51_fu_980_p2 = ($signed(lhs_52_fu_968_p3) + $signed(sext_ln703_32_fu_976_p1));

assign ret_V_52_fu_1293_p2 = ($signed(lhs_53_fu_1282_p3) + $signed(sext_ln703_33_fu_1289_p1));

assign ret_V_53_fu_1323_p2 = (lhs_54_fu_1315_p3 + r_V_76_fu_1299_p2);

assign ret_V_54_fu_1612_p2 = (lhs_55_fu_1605_p3 + r_V_77_fu_1599_p2);

assign ret_V_55_fu_1646_p2 = ($signed(lhs_56_fu_1634_p3) + $signed(sext_ln703_34_fu_1642_p1));

assign ret_V_56_fu_1931_p2 = (lhs_57_fu_1924_p3 + r_V_79_fu_1918_p2);

assign ret_V_57_fu_1961_p2 = (lhs_58_fu_1953_p3 + r_V_80_fu_1937_p2);

assign ret_V_58_fu_2282_p2 = ($signed(lhs_59_fu_2271_p3) + $signed(sext_ln703_35_fu_2278_p1));

assign ret_V_59_fu_2316_p2 = ($signed(lhs_60_fu_2304_p3) + $signed(sext_ln703_36_fu_2312_p1));

assign ret_V_5_fu_729_p2 = ($signed(lhs_6_fu_718_p3) + $signed(sext_ln703_1_fu_725_p1));

assign ret_V_60_fu_2637_p2 = ($signed(lhs_61_fu_2626_p3) + $signed(sext_ln703_37_fu_2633_p1));

assign ret_V_61_fu_2671_p2 = ($signed(lhs_62_fu_2659_p3) + $signed(sext_ln703_38_fu_2667_p1));

assign ret_V_62_fu_2980_p2 = (lhs_63_fu_2973_p3 + r_V_85_fu_2967_p2);

assign ret_V_63_fu_3014_p2 = ($signed(lhs_64_fu_3002_p3) + $signed(sext_ln703_39_fu_3010_p1));

assign ret_V_64_fu_680_p2 = ($signed(sext_ln728_4_fu_672_p1) + $signed(sext_ln703_40_fu_676_p1));

assign ret_V_65_fu_1009_p2 = (lhs_66_fu_1002_p3 + r_V_89_fu_996_p2);

assign ret_V_66_fu_1039_p2 = (lhs_67_fu_1031_p3 + r_V_90_fu_1015_p2);

assign ret_V_67_fu_1352_p2 = (lhs_68_fu_1345_p3 + r_V_91_fu_1339_p2);

assign ret_V_68_fu_1382_p2 = (lhs_69_fu_1374_p3 + r_V_92_fu_1358_p2);

assign ret_V_69_fu_1679_p2 = ($signed(lhs_70_fu_1668_p3) + $signed(sext_ln703_41_fu_1675_p1));

assign ret_V_6_fu_771_p2 = (lhs_7_fu_763_p3 + r_V_14_fu_747_p2);

assign ret_V_70_fu_1713_p2 = ($signed(lhs_71_fu_1701_p3) + $signed(sext_ln703_42_fu_1709_p1));

assign ret_V_71_fu_1994_p2 = ($signed(lhs_72_fu_1983_p3) + $signed(sext_ln703_43_fu_1990_p1));

assign ret_V_72_fu_2024_p2 = (lhs_73_fu_2016_p3 + r_V_96_fu_2000_p2);

assign ret_V_73_fu_2349_p2 = ($signed(lhs_74_fu_2338_p3) + $signed(sext_ln703_44_fu_2345_p1));

assign ret_V_74_fu_2383_p2 = ($signed(lhs_75_fu_2371_p3) + $signed(sext_ln703_45_fu_2379_p1));

assign ret_V_75_fu_2704_p2 = ($signed(lhs_76_fu_2693_p3) + $signed(sext_ln703_46_fu_2700_p1));

assign ret_V_76_fu_2738_p2 = ($signed(lhs_77_fu_2726_p3) + $signed(sext_ln703_47_fu_2734_p1));

assign ret_V_77_fu_3043_p2 = (lhs_78_fu_3036_p3 + r_V_101_fu_3030_p2);

assign ret_V_78_fu_3077_p2 = ($signed(lhs_79_fu_3065_p3) + $signed(sext_ln703_48_fu_3073_p1));

assign ret_V_7_fu_1084_p2 = ($signed(lhs_8_fu_1073_p3) + $signed(sext_ln703_2_fu_1080_p1));

assign ret_V_8_fu_1130_p2 = ($signed(lhs_9_fu_1118_p3) + $signed(sext_ln703_3_fu_1126_p1));

assign ret_V_9_fu_1423_p2 = ($signed(lhs_10_fu_1412_p3) + $signed(sext_ln703_4_fu_1419_p1));

assign ret_V_fu_464_p2 = ($signed(sext_ln728_fu_456_p1) + $signed(sext_ln703_fu_460_p1));

assign sext_ln1115_10_fu_438_p0 = input_0_q1;

assign sext_ln1115_10_fu_438_p1 = sext_ln1115_10_fu_438_p0;

assign sext_ln1115_12_fu_700_p1 = reg_389;

assign sext_ln1115_16_fu_739_p0 = input_0_q0;

assign sext_ln1115_16_fu_739_p1 = sext_ln1115_16_fu_739_p0;

assign sext_ln1115_17_fu_743_p0 = input_0_q0;

assign sext_ln1115_17_fu_743_p1 = sext_ln1115_17_fu_743_p0;

assign sext_ln1115_20_fu_1063_p1 = reg_389;

assign sext_ln1115_21_fu_1090_p0 = input_0_q0;

assign sext_ln1115_21_fu_1090_p1 = sext_ln1115_21_fu_1090_p0;

assign sext_ln1115_24_fu_1398_p1 = reg_389;

assign sext_ln1115_25_fu_1402_p1 = reg_389;

assign sext_ln1115_26_fu_1429_p0 = input_0_q0;

assign sext_ln1115_26_fu_1429_p1 = sext_ln1115_26_fu_1429_p0;

assign sext_ln1115_27_fu_1433_p0 = input_0_q0;

assign sext_ln1115_27_fu_1433_p1 = sext_ln1115_27_fu_1433_p0;

assign sext_ln1115_29_fu_1733_p1 = reg_389;

assign sext_ln1115_30_fu_1756_p1 = $signed(input_0_q0);

assign sext_ln1115_32_fu_2044_p1 = reg_389;

assign sext_ln1115_34_fu_2075_p0 = input_0_q0;

assign sext_ln1115_34_fu_2075_p1 = sext_ln1115_34_fu_2075_p0;

assign sext_ln1115_38_fu_2403_p1 = reg_389;

assign sext_ln1115_39_fu_2430_p0 = input_0_q0;

assign sext_ln1115_39_fu_2430_p1 = sext_ln1115_39_fu_2430_p0;

assign sext_ln1115_40_fu_2434_p0 = input_0_q0;

assign sext_ln1115_40_fu_2434_p1 = sext_ln1115_40_fu_2434_p0;

assign sext_ln1115_42_fu_2754_p1 = reg_389;

assign sext_ln1115_43_fu_2758_p1 = reg_389;

assign sext_ln1115_44_fu_2781_p0 = input_0_q1;

assign sext_ln1115_44_fu_2781_p1 = sext_ln1115_44_fu_2781_p0;

assign sext_ln1115_5_fu_402_p1 = reg_389;

assign sext_ln1192_1_fu_568_p1 = $signed(r_V_56_fu_550_p2);

assign sext_ln1192_2_fu_618_p1 = $signed(lhs_50_fu_610_p3);

assign sext_ln1192_3_fu_622_p1 = $signed(r_V_72_fu_604_p2);

assign sext_ln1192_fu_564_p1 = $signed(lhs_35_fu_556_p3);

assign sext_ln703_10_fu_514_p1 = $signed(r_V_40_fu_496_p2);

assign sext_ln703_11_fu_800_p1 = $signed(r_V_41_fu_787_p2);

assign sext_ln703_12_fu_834_p1 = $signed(r_V_42_fu_810_p2);

assign sext_ln703_13_fu_1159_p1 = $signed(r_V_43_fu_1146_p2);

assign sext_ln703_14_fu_1193_p1 = $signed(r_V_44_fu_1169_p2);

assign sext_ln703_15_fu_1490_p1 = $signed(r_V_45_fu_1477_p2);

assign sext_ln703_16_fu_2144_p1 = $signed(r_V_49_fu_2131_p2);

assign sext_ln703_17_fu_2178_p1 = $signed(r_V_50_fu_2154_p2);

assign sext_ln703_18_fu_2499_p1 = $signed(r_V_51_fu_2486_p2);

assign sext_ln703_19_fu_2533_p1 = $signed(r_V_52_fu_2509_p2);

assign sext_ln703_1_fu_725_p1 = $signed(r_V_12_fu_712_p2);

assign sext_ln703_20_fu_2846_p1 = $signed(r_V_53_fu_2833_p2);

assign sext_ln703_21_fu_2880_p1 = $signed(r_V_54_fu_2856_p2);

assign sext_ln703_22_fu_871_p1 = $signed(r_V_57_fu_854_p2);

assign sext_ln703_23_fu_905_p1 = $signed(r_V_58_fu_881_p2);

assign sext_ln703_24_fu_1226_p1 = $signed(r_V_59_fu_1213_p2);

assign sext_ln703_25_fu_2211_p1 = $signed(r_V_65_fu_2198_p2);

assign sext_ln703_26_fu_2245_p1 = $signed(r_V_66_fu_2221_p2);

assign sext_ln703_27_fu_2566_p1 = $signed(r_V_67_fu_2553_p2);

assign sext_ln703_28_fu_2600_p1 = $signed(r_V_68_fu_2576_p2);

assign sext_ln703_29_fu_2913_p1 = $signed(r_V_69_fu_2900_p2);

assign sext_ln703_2_fu_1080_p1 = $signed(r_V_16_fu_1067_p2);

assign sext_ln703_30_fu_2947_p1 = $signed(r_V_70_fu_2923_p2);

assign sext_ln703_31_fu_942_p1 = $signed(r_V_73_fu_925_p2);

assign sext_ln703_32_fu_976_p1 = $signed(r_V_74_fu_952_p2);

assign sext_ln703_33_fu_1289_p1 = $signed(r_V_75_fu_1276_p2);

assign sext_ln703_34_fu_1642_p1 = $signed(r_V_78_fu_1618_p2);

assign sext_ln703_35_fu_2278_p1 = $signed(r_V_81_fu_2265_p2);

assign sext_ln703_36_fu_2312_p1 = $signed(r_V_82_fu_2288_p2);

assign sext_ln703_37_fu_2633_p1 = $signed(r_V_83_fu_2620_p2);

assign sext_ln703_38_fu_2667_p1 = $signed(r_V_84_fu_2643_p2);

assign sext_ln703_39_fu_3010_p1 = $signed(r_V_86_fu_2986_p2);

assign sext_ln703_3_fu_1126_p1 = $signed(r_V_18_fu_1102_p2);

assign sext_ln703_40_fu_676_p1 = $signed(r_V_88_fu_658_p2);

assign sext_ln703_41_fu_1675_p1 = $signed(r_V_93_fu_1662_p2);

assign sext_ln703_42_fu_1709_p1 = $signed(r_V_94_fu_1685_p2);

assign sext_ln703_43_fu_1990_p1 = $signed(r_V_95_fu_1977_p2);

assign sext_ln703_44_fu_2345_p1 = $signed(r_V_97_fu_2332_p2);

assign sext_ln703_45_fu_2379_p1 = $signed(r_V_98_fu_2355_p2);

assign sext_ln703_46_fu_2700_p1 = $signed(r_V_99_fu_2687_p2);

assign sext_ln703_47_fu_2734_p1 = $signed(r_V_100_fu_2710_p2);

assign sext_ln703_48_fu_3073_p1 = $signed(r_V_102_fu_3049_p2);

assign sext_ln703_4_fu_1419_p1 = $signed(r_V_20_fu_1406_p2);

assign sext_ln703_5_fu_2061_p1 = $signed(r_V_28_fu_2048_p2);

assign sext_ln703_6_fu_2111_p1 = $signed(r_V_30_fu_2087_p2);

assign sext_ln703_7_fu_2420_p1 = $signed(r_V_32_fu_2407_p2);

assign sext_ln703_8_fu_2466_p1 = $signed(r_V_34_fu_2442_p2);

assign sext_ln703_9_fu_2813_p1 = $signed(r_V_38_fu_2789_p2);

assign sext_ln703_fu_460_p1 = $signed(r_V_10_fu_442_p2);

assign sext_ln728_1_fu_510_p1 = $signed(lhs_20_fu_502_p3);

assign sext_ln728_4_fu_672_p1 = $signed(lhs_65_fu_664_p3);

assign sext_ln728_fu_456_p1 = $signed(lhs_fu_448_p3);

assign tmp_11_fu_2448_p4 = {{ret_V_15_fu_2424_p2[55:24]}};

assign tmp_13_fu_2795_p4 = {{ret_V_17_fu_2775_p2[55:24]}};

assign tmp_14_fu_860_p3 = {{tmp_reg_3158}, {24'd0}};

assign tmp_16_fu_816_p4 = {{ret_V_20_fu_804_p2[55:24]}};

assign tmp_18_fu_1175_p4 = {{ret_V_22_fu_1163_p2[55:24]}};

assign tmp_1_fu_753_p4 = {{ret_V_5_fu_729_p2[55:24]}};

assign tmp_20_fu_1506_p4 = {{ret_V_24_fu_1494_p2[55:24]}};

assign tmp_22_fu_1825_p4 = {{ret_V_26_fu_1813_p2[55:24]}};

assign tmp_24_fu_2160_p4 = {{ret_V_28_fu_2148_p2[55:24]}};

assign tmp_26_fu_2515_p4 = {{ret_V_30_fu_2503_p2[55:24]}};

assign tmp_28_fu_2862_p4 = {{ret_V_32_fu_2850_p2[55:24]}};

assign tmp_30_fu_887_p4 = {{ret_V_35_fu_875_p2[55:24]}};

assign tmp_32_fu_1242_p4 = {{ret_V_37_fu_1230_p2[55:24]}};

assign tmp_34_fu_1565_p4 = {{ret_V_39_fu_1553_p2[55:24]}};

assign tmp_36_fu_1884_p4 = {{ret_V_41_fu_1872_p2[55:24]}};

assign tmp_38_fu_2227_p4 = {{ret_V_43_fu_2215_p2[55:24]}};

assign tmp_3_fu_1108_p4 = {{ret_V_7_fu_1084_p2[55:24]}};

assign tmp_40_fu_2582_p4 = {{ret_V_45_fu_2570_p2[55:24]}};

assign tmp_42_fu_2929_p4 = {{ret_V_47_fu_2917_p2[55:24]}};

assign tmp_43_fu_931_p3 = {{tmp_29_reg_3163}, {24'd0}};

assign tmp_44_fu_958_p4 = {{ret_V_50_fu_946_p2[55:24]}};

assign tmp_46_fu_1305_p4 = {{ret_V_52_fu_1293_p2[55:24]}};

assign tmp_48_fu_1624_p4 = {{ret_V_54_fu_1612_p2[55:24]}};

assign tmp_50_fu_1943_p4 = {{ret_V_56_fu_1931_p2[55:24]}};

assign tmp_52_fu_2294_p4 = {{ret_V_58_fu_2282_p2[55:24]}};

assign tmp_54_fu_2649_p4 = {{ret_V_60_fu_2637_p2[55:24]}};

assign tmp_56_fu_2992_p4 = {{ret_V_62_fu_2980_p2[55:24]}};

assign tmp_59_fu_1021_p4 = {{ret_V_65_fu_1009_p2[55:24]}};

assign tmp_5_fu_1443_p4 = {{ret_V_9_fu_1423_p2[55:24]}};

assign tmp_61_fu_1364_p4 = {{ret_V_67_fu_1352_p2[55:24]}};

assign tmp_63_fu_1691_p4 = {{ret_V_69_fu_1679_p2[55:24]}};

assign tmp_65_fu_2006_p4 = {{ret_V_71_fu_1994_p2[55:24]}};

assign tmp_67_fu_2361_p4 = {{ret_V_73_fu_2349_p2[55:24]}};

assign tmp_69_fu_2716_p4 = {{ret_V_75_fu_2704_p2[55:24]}};

assign tmp_71_fu_3055_p4 = {{ret_V_77_fu_3043_p2[55:24]}};

assign tmp_7_fu_1766_p4 = {{ret_V_11_fu_1750_p2[55:24]}};

assign tmp_9_fu_2093_p4 = {{ret_V_13_fu_2065_p2[55:24]}};

assign trunc_ln708_1_fu_540_p4 = {{r_V_55_fu_534_p2[51:24]}};

assign trunc_ln708_2_fu_594_p4 = {{r_V_71_fu_588_p2[50:24]}};

assign trunc_ln708_3_fu_648_p4 = {{r_V_87_fu_642_p2[54:24]}};

assign trunc_ln708_s_fu_486_p4 = {{r_V_39_fu_480_p2[54:24]}};

assign trunc_ln_fu_416_p4 = {{r_V_8_fu_410_p2[53:24]}};

endmodule //nn_inference_hwmm_layer3
